module.exports = {
  type: {
    User: false,
    UsersPermissionsRole: false,
    UsersPermissionsMe: false,
    UsersPermissionsLoginPayload: false,
    UploadFile: false,
    UserPermissionsPasswordPayload: false,
    UsersPermissionsLoginInput: false
  },
  resolver: {
    Query: {
      user: false,
      users: false,
      me: false,
      role: false,
      roles: false,
      files: false,
    },
    Mutation: {
      createUser: false,
      createRole: false,
      updateRole: false,
      updateUser: false,
      deleteRole: false,
      deleteUser: false,
      login: false,
      register: false,
      resetPassword: false,
      forgotPassword: false,
      emailConfirmation: false,
      updateDocument: false,
      deleteDocument: false,
      updatePartner: false,
      deletePartner: false,
      createPoliticianResult: false,
      updatePoliticianResult: false,
      deletePoliticianResult: false,
      createPost: false,
      updatePost: false,
      deletePost: false,
      createTalk: false,
      updateTalk: false,
      deleteTalk: false,
      deleteFile: false,
      upload: false,
      multipleUpload: false,
      updateFileInfo: false,
    },
  },
};
